### ISSUE TITLE
cannot find symbol lifecycle.FlutterLifecycleAdapter error

### ISSUE THREAD

**Issue by EhsanBrd** [juicycleff/flutter-unity-view-widget#304]
Hello friends
Have Good time.
I encountered this problem when I upgraded **Unity Widgets to version 3.**
I researched for a few days and they told me similar examples about changing the **dependencies version**, but again this did not work. Thank you for your help.

There is an error in the screenshot below :
![Capture](https://user-images.githubusercontent.com/25132414/105642735-b33f9900-5ea0-11eb-98b1-83f0b34916e7.JPG)

**Comment by EhsanBrd** [comment]
@juicycleff Could you please help me bro ?!

**Comment by juicycleff** [comment]
@EhsanBrd have you tried migrate your project to flutter embedding V2.

**Comment by EhsanBrd** [comment]
@juicycleff yes i do.

![2](https://user-images.githubusercontent.com/25132414/105709172-9ea7e300-5f2a-11eb-8743-09b55751dc19.JPG)

**Comment by EhsanBrd** [comment]
@juicycleff I don't have any extra code , 
after upgrade my dart and flutter.
I just add   flutter_unity_widget: ^3.0.2 to project and run...

**Comment by juicycleff** [comment]
It's actually weird because I used the project this weekend. I will take a look today and see if that dependency was updated

**Comment by EhsanBrd** [comment]
@juicycleff Thank you for your attention, I also have no problem with older versions, this problem has occurred since version 2.
I am waiting for your answer...

**Comment by juicycleff** [comment]
@EhsanBrd seen this https://github.com/flutter/flutter/issues/65012#issuecomment-685686708

**Comment by kaushikb1996** [comment]
Facing the same issue, even with the newer flutter & dart version mentioned by @EhsanBrd and I have not even used clipboard manager, I have made even a single file app but it's still the same.

**Comment by EhsanBrd** [comment]
> @EhsanBrd seen this [flutter/flutter#65012 (comment)](https://github.com/flutter/flutter/issues/65012#issuecomment-685686708)

Hi
@juicycleff thank's for answer, 
still not work , I don't have use any clipboard manager or other dependencies , I think it's about this version of flutter_unity_widget !

my flutter run --release --verbose  , Logs :
[Problem_Logs.txt](https://github.com/juicycleff/flutter-unity-view-widget/files/5874622/Problem_Logs.txt)

**Comment by EhsanBrd** [comment]
> Facing the same issue, even with the newer flutter & dart version mentioned by @EhsanBrd and I have not even used clipboard manager, I have made even a single file app with no external dependencies but it's still the same.
> 
> > Buildingplugin flutter_plugin_android_lifecycle...
> > Running Gradle task assembleAarRelease...
> > C:\Users\username\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.11\android\src\main\java\io\flutter\embedding\engine\plugins\lifecycle\FlutterLifecycleAdapter.java:8: error: package androidx.lifecycle does not exist
> > import androidx.lifecycle.Lifecycle;
> > ^
> > C:\Users\username\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.11\android\src\main\java\io\flutter\embedding\engine\plugins\lifecycle\FlutterLifecycleAdapter.java:22: error: cannot find symbol
> > public static Lifecycle getActivityLifecycle(
> > ^
> > symbol:   class Lifecycle
> > location: class FlutterLifecycleAdapter
> > 2 errors
> > FAILURE: Build failed with an exception.
> > 
> > * What went wrong:
> >   Execution failed for task :compileReleaseJavaWithJavac.
> > 
> > > Compilation failed; see the compiler error output for details.
> > 
> > 
> > 
> > * Try:
> >   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> > * Get more help at https://help.gradle.org
> > 
> > BUILD FAILED in 0s
> > Exception: The plugin flutter_plugin_android_lifecycle could not be built due to the issue above.

**Comment by juicycleff** [comment]
@EhsanBrd please use v 3.0.3

**Comment by EhsanBrd** [comment]
> @EhsanBrd please use v 3.0.3

Thank you very much, the problem was solved...

**Comment by tariq-alskran** [comment]
after update to 3.0.3

FAILURE: Build failed with an exception.

Where:
Build file 'C:\flutter.pub-cache\hosted\pub.dartlang.org\flutter_unity_widget-3.0.3\android\build.gradle' line: 47

What went wrong:
A problem occurred evaluating project ':flutter_unity_widget'.

Project with path ':unityLibrary' could not be found in project ':flutter_unity_widget'.
