### ISSUE TITLE
Unable to build with Flutter 2.2.0+

### ISSUE THREAD

**Issue by ArneSaknussemm89** [juicycleff/flutter-unity-view-widget#416]
**Describe the bug**
When using Flutter ^2.2.0, there are errors thrown:
```
2 warnings generated.
    Undefined symbols for architecture arm64:
      "_OnUnitySceneLoaded", referenced from:
          _NativeAPI_OnUnitySceneLoaded_mB0837ED51EE99E965D15D2BA23B6287C0793D1DF in Assembly-CSharp.o
         (maybe you meant: _NativeAPI_OnUnitySceneLoaded_mB0837ED51EE99E965D15D2BA23B6287C0793D1DF)
      "_OnUnityMessage", referenced from:
          _NativeAPI_OnUnityMessage_mEB20277B0A0AF2ECDFB0DA7E49113BEB51493550 in Assembly-CSharp.o
         (maybe you meant: _NativeAPI_OnUnityMessage_mEB20277B0A0AF2ECDFB0DA7E49113BEB51493550)
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
```

**To Reproduce**
1. Configure a basic Flutter app
2. Configure the plugin
3. Start a debug build for a connected device

**Expected behavior**
The build would succeed. (This also happens on another project that builds fine on Flutter ^2.0.0

**Screenshots**

**Unity (please complete the following information):**
 - OS: Mac OSX Big Sur
 - Version: 11.2.3

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS
 - Version 14.4.2

**Additional context**
On an existing project using this plugin version 4.2.0 and Flutter 2.0.1 it builds properly. Updating to Flutter 2.2.0 or 2.2.1 and it throws the above errors.

**Comment by WouterVandenputte** [comment]
![image](https://user-images.githubusercontent.com/23052815/122685392-5657cd00-d20b-11eb-9597-d481be98eb84.png)
Did you check the ARM64 architecture in the player settings?

**Comment by WouterVandenputte** [comment]
![image](https://user-images.githubusercontent.com/23052815/122685429-915a0080-d20b-11eb-9330-0dd91a4c096e.png)
Did you check the ARM64 in the player settings?

**Comment by juicycleff** [comment]
You might have a bad xcode config setup @ArneSaknussemm89, try cleaning and also follow @WouterVandenputte guide
