### PR TITLE
Fix broken UnityReady trigger in iOS exports.

### PR DESCRIPTION
**Pull request by timbotimbo**
## Description

This is based on #554 and is the cause for some white screen issues on iOS.
#595 seems to be a workaround for the bug caused by this.

The `XcodePostBuild.cs` script adds a notification trigger into `\ios\UnityLibrary\Classes\UnityAppController.mm`, which is used by the plugin.
The script searches for `}` to find the end of the `startUnity` function and places additional lines there, which works for older Unity versions like 2019.4.23 or 2020.3.6.
This fails with newer Unity versions because of an if-statement that provides an earlier `}`.

## 
The old and correct way:
```diff
{ // 2020.3.6f1
    ...

    AVAudioSession* audioSession = [AVAudioSession sharedInstance];
    [audioSession setActive: YES error: nil];
    [audioSession addObserver: self forKeyPath: @"outputVolume" options: 0 context: nil];
    UnityUpdateMuteState([audioSession outputVolume] < 0.01f ? 1 : 0);

#if UNITY_REPLAY_KIT_AVAILABLE
    void InitUnityReplayKit();  // Classes/Unity/UnityReplayKit.mm

    InitUnityReplayKit();
#endif
-}
+    // Modified by https://github.com/juicycleff/flutter-unity-view-widget
+   [[NSNotificationCenter defaultCenter] postNotificationName: @"UnityReady" object:self];
+}
```
## 
Newer broken outputs:
```diff
{ //2020.3.31f1
    ...

    AVAudioSession* audioSession = [AVAudioSession sharedInstance];
    [audioSession setCategory: AVAudioSessionCategoryAmbient error: nil];
    if (UnityIsAudioManagerAvailableAndEnabled())
    {
        if (UnityShouldPrepareForIOSRecording())
        {
            [audioSession setCategory: AVAudioSessionCategoryPlayAndRecord error: nil];
-       }
+    // Modified by https://github.com/juicycleff/flutter-unity-view-widget
+   [[NSNotificationCenter defaultCenter] postNotificationName: @"UnityReady" object:self];
+}
        else if (UnityShouldMuteOtherAudioSources())
        {
            [audioSession setCategory: AVAudioSessionCategorySoloAmbient error: nil];
        }
    }

    [audioSession setActive: YES error: nil];
    [audioSession addObserver: self forKeyPath: @"outputVolume" options: 0 context: nil];
    UnityUpdateMuteState([audioSession outputVolume] < 0.01f ? 1 : 0);

#if UNITY_REPLAY_KIT_AVAILABLE
    void InitUnityReplayKit();  // Classes/Unity/UnityReplayKit.mm

    InitUnityReplayKit();
#endif
}
```

## Fix
This is an adaptation of the fix suggested in #554.
It removes `line.Trim()` in the string replacement so that it can skip a `}` that has indentation.
The regex is used as a precaution to make the match more flexible with possible spaces/tabs/line breaks at the end of the line.

While testing Untiy 2020.3.x I also fixed a small compilation error in `Build.cs`.

## Testing
If you want to test this change, don't forget to delete the unityLibrary folder before trying a new export.
The export script will skip this file if it has been edited already.

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [X] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by kamami** [comment]
Your fork unfortunately does not fix the issue for Unity 2021.3.16f1.
I still get the white screen starting unity the first time.
Tested it on iOS 16.2 and the latest flutter stable channel.

**Comment by timbotimbo** [comment]
Can you post the contents of your `ios\UnityLibrary\Classes\UnityAppController.mm` after an export?

You might have a different issue with similar symptoms.

Even if this doesn't fix all related bugs, it think we should include it as the export currently doesn't do what it was intended to do.

**Comment by timbotimbo** [comment]
Just did some additional testing.
This still works on the latest Unity versions: `2021.3.21f1`, `2022.2.12f1` and `2023.1.0b9`
